CREATE TABLE APP.PURCHASE_ORDER (
ID  INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SUPPLIER_ID INTEGER,
QUOTATION_ID INTEGER,
USER_ID INTEGER,
CREATED_DATE DATE,
LASTMODIFIED_DATE DATE );
